In [ ]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.17.0


In [ ]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [ ]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

/usr/local/lib/python3.10/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [ ]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.02510792,  0.15751976, -0.04500807, -0.06380027, -0.6867149 ,
         0.2548046 , -0.14847788,  0.31554323, -0.12676907, -0.15099877]],
      dtype=float32)

In [ ]:
tf.nn.softmax(predictions).numpy()

array([[0.09943726, 0.11936124, 0.097478  , 0.09566328, 0.05131176,
        0.1315569 , 0.08789623, 0.13979514, 0.08982521, 0.08767494]],
      dtype=float32)

In [ ]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
loss_fn(y_train[:1], predictions).numpy()

2.0283158

In [ ]:
model.compile(optimizer='adam',
              loss = loss_fn,
              metrics=['accuracy'])

In [ ]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.8599 - loss: 0.4815
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - accuracy: 0.9535 - loss: 0.1519
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9666 - loss: 0.1066
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - accuracy: 0.9718 - loss: 0.0900
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - accuracy: 0.9769 - loss: 0.0740


In [ ]:
model.evaluate(x_test, y_test, verbose=2)

313/313 - 1s - 2ms/step - accuracy: 0.9773 - loss: 0.0768


[0.07681939750909805, 0.9772999882698059]

In [ ]:
probability_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.1296754e-09, 1.4929387e-09, 4.0830466e-05, 3.1984693e-03,
        1.2322871e-11, 4.3037790e-06, 5.9508952e-13, 9.9672276e-01,
        1.6948121e-05, 1.6671385e-05],
       [4.4530402e-08, 2.5619357e-04, 9.9973470e-01, 7.3478250e-06,
        4.0361378e-15, 1.8091541e-07, 1.9113432e-07, 1.0741158e-13,
        1.2612015e-06, 9.6234225e-15],
       [3.3840712e-07, 9.9500304e-01, 2.5691077e-04, 5.9243299e-05,
        1.9148151e-04, 7.2485753e-05, 4.2821081e-05, 3.7052762e-03,
        6.5873895e-04, 9.6677804e-06],
       [9.9997652e-01, 2.0773478e-11, 4.4279263e-06, 1.1254470e-08,
        8.9591490e-09, 8.1511064e-07, 1.7118628e-05, 2.5650652e-07,
        7.9215159e-09, 8.1685147e-07],
       [1.2648089e-06, 1.5094213e-10, 5.1230942e-05, 2.9472400e-08,
        9.9897408e-01, 2.9279158e-06, 2.8669149e-06, 1.6506085e-04,
        1.6206243e-06, 8.0096419e-04]], dtype=float32)>